### ISSUE TITLE
报错了,变量 source找不到符号

### ISSUE THREAD

**Issue by BestYun** [liranhao/recognition_qrcode#10]
recognition_qrcode-1.0.2/android/src/main/java/com/recognition/qrcode/recognition_qrcode/RecognitionQrcodePlugin.java:184: 错误: 找不到符号
                com.google.zxing.Result res = new MultiFormatReader().decode(new BinaryBitmap(new GlobalHistogramBinarizer(source)), HINTS);
                                                                                          ^
  符号:   变量 source
  位置: 类 RecognitionQrcodePlugin

**Comment by liranhao** [comment]
> recognition_qrcode-1.0.2/android/src/main/java/com/recognition/qrcode/recognition_qrcode/RecognitionQrcodePlugin.java:184: 错误: 找不到符号 com.google.zxing.Result res = new MultiFormatReader().decode(new BinaryBitmap(new GlobalHistogramBinarizer(source)), HINTS); ^ 符号: 变量 source 位置: 类 RecognitionQrcodePlugin

先使用上个版本吧，最新版本有点问题，我改下

**Comment by liranhao** [comment]
1.0.2+1版本已修复这个问题
