### ISSUE TITLE
'ZBarSDK.h' file not found

### ISSUE THREAD

**Issue by Dove900412** [liranhao/recognition_qrcode#12]
Could not build the precompiled application for the device.
Lexical or Preprocessor Issue (Xcode): 'ZBarSDK.h' file not found
/Users/xx/.pub-cache/hosted/pub.flutter-io.cn/recognition_qrcode-1.0.2+1/ios/Classes/RecognitionQrcodePlugin.m:3:8

**Comment by Dove900412** [comment]
v1.0.2+1

**Comment by liranhao** [comment]
> 

删除pod，重新pod install 试下

**Comment by Dove900412** [comment]
可以了
