### ISSUE TITLE
从相册选择图片，识别报错

### ISSUE THREAD

**Issue by ShuangZiMoYin** [liranhao/recognition_qrcode#14]
I/flutter (13545): 图片路径：/data/user/0/in.kahub.labelexpert/cache/9aa06118-247b-48a1-9955-b5169fa5c119/P30624-143122(1).jpg
W/System.err(13545): com.google.zxing.NotFoundException
E/flutter (13545): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(-1, Image parsing failed, null, null)
E/flutter (13545): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter (13545): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter (13545): <asynchronous suspension>
E/flutter (13545): #2      RecognitionQrcode.recognition (package:recognition_qrcode/recognition_qrcode.dart:16:18)
E/flutter (13545): <asynchronous suspension>

**Comment by liranhao** [comment]
图片没识别出来，建议压缩下图片大小，或者减少二维码字符串的长度
