### ISSUE TITLE
Can you fix the recognition_qrcode？

### ISSUE THREAD

**Issue by shang1219178163** [liranhao/recognition_qrcode#18]
https://pub.dev/packages/recognition_qrcode
<img width="456" alt="截屏2024-05-28 17 41 37" src="https://github.com/liranhao/recognition_qrcode/assets/3699729/b5c6e67b-9225-4e85-8716-11e9b5c8e8e7">

**Comment by liranhao** [comment]
OK， 今晚更新

**Comment by liranhao** [comment]
updated
