### ISSUE TITLE
Can't read qrcode from image

### ISSUE THREAD

**Issue by SanSanNiang** [liranhao/recognition_qrcode#2]
从手机相册选择的二维码图，无法解析，返回为null

**Comment by liranhao** [comment]
请问是iOS还是安卓？系统版本是多少？

**Comment by liranhao** [comment]
> 从手机相册选择的二维码图，无法解析，返回为null

请问是iOS还是安卓？系统版本是多少

**Comment by SanSanNiang** [comment]
安卓手机，系统版本 7.1.1

**Comment by liranhao** [comment]
> 安卓手机，系统版本 7.1.1

好的，我测试一下

**Comment by liranhao** [comment]
> 安卓手机，系统版本 7.1.1

我测试了一下安卓7.1.1是能正常解析的，你换下手机试下，可能和手机型号有关，或者图片大小有关，如果图片太大可以压缩一下再识别
