### ISSUE TITLE
使用相机拍照问题

### ISSUE THREAD

**Issue by hanklee9820** [liranhao/recognition_qrcode#23]
使用[Camera插件](https://pub.dev/packages/camera)拍照传入识别错误。拿到的image的imageOrientation是right并不是up。所以icon图标的位置错误了

**Comment by hanklee9820** [comment]
![IMG_0128 2](https://github.com/user-attachments/assets/343b67c7-1bdf-49f3-98a3-b35f8ac5b0e6)

**Comment by liranhao** [comment]
好的，我有时间看下

**Comment by liranhao** [comment]
> imageOrientation

麻烦问下，这是iOS还是安卓的？

**Comment by liranhao** [comment]
<img width="650" alt="image" src="https://github.com/user-attachments/assets/b1a347ef-8221-4236-9704-13ef3561da91">
我看了下，iOS下有获取image的imageOrientation，如果这个图片识别错误，要看下是不是图片本身的imageOrientation是不是有问题

**Comment by liranhao** [comment]
再问下你是传的base 64还是本地路径？

**Comment by liranhao** [comment]
特殊处理了下imageOrientation，已发布新版本，你试下

**Comment by hanklee9820** [comment]
不好意思。我用的是拍照存本地路径方式，我这边也是用image插件旋转图片解决的。跟imageOrientation一样的
