### ISSUE TITLE
能否通过判断，屏蔽 iOS 模拟器，让应用能在模拟器上运行呢

### ISSUE THREAD

**Issue by evanscai** [liranhao/recognition_qrcode#24]
引入这个库后模拟器上运行调试不了了，能否加入宏或者其它判断，保证应用能在模拟器上运行，从而不影响开发其他功能

**Comment by liranhao** [comment]
我试下

**Comment by liranhao** [comment]
已解决，模拟器不支持识别，但可以在模拟器上运行

**Comment by evanscai** [comment]
> 已解决，模拟器不支持识别，但可以在模拟器上运行

感谢

**Comment by evanscai** [comment]
另外再提个小问题，README.md 里的 Demo 代码写错了，我看源代码里已经改成用`RecognitionManager.recognition`，但是 README.md 里写的是`RecognitionQrcode.recognition`。

现在得这样写
```
RecognitionManager.recognition(url).then((result) {
    print("recognition: ${result.code}");
    print("recognition: ${result.value}");
}
```

**Comment by liranhao** [comment]
好的，我改下
