### ISSUE TITLE
安卓相册中识别二维码识别失败

### ISSUE THREAD

**Issue by youwuxiangsheng** [liranhao/recognition_qrcode#3]
![image](https://user-images.githubusercontent.com/14975026/105944166-bc498980-609d-11eb-97c2-a5dbdea855df.png)
W/System.err(10224): com.google.zxing.NotFoundException
E/flutter (10224): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(-1, Image parsing failed, null, null)
E/flutter (10224): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter (10224): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter (10224): <asynchronous suspension>
E/flutter (10224): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (10224): #3      RecognitionQrcode.recognition (package:recognition_qrcode/recognition_qrcode.dart:16:33)
E/flutter (10224): #4      CustomQrCode.build.<anonymous closure> (package:mz/components/custom_qr_code.component.dart:43:48)
E/flutter (10224): <asynchronous suspension>
E/flutter (10224): #5      CustomQrCode.build.<anonymous closure> (package:mz/components/custom_qr_code.component.dart)
E/flutter (10224): #6      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter (10224): #7      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter (10224): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (10224): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (10224): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (10224): #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter (10224): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter (10224): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter (10224): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (10224): #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (10224): #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (10224): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (10224): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter (10224): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (10224): #20     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (10224): #21     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (10224): #22     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (10224): #23     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (10224): #24     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (10224): #25     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (10224): #26     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (10224): #27     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (10224): #28     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)

**Comment by liranhao** [comment]
能发一下机型和系统版本还有要识别的二维码吗？

**Comment by youwuxiangsheng** [comment]
小米9  安卓9 MIUI 10.2.35
![image](https://user-images.githubusercontent.com/14975026/105966110-30485980-60bf-11eb-94ed-ecd6220ba657.png)

**Comment by liranhao** [comment]
这张二维码解析确实有问题哦，我用iOS版微信识别也没识别出来，但是可以扫码扫出来，希望可以放大一些图片，太密集比较难解析
![411611737659_ pic_hd](https://user-images.githubusercontent.com/15797388/105967093-6f2adf00-60c0-11eb-97c8-4c4adab4c824.jpg)

**Comment by liranhao** [comment]
二维码本身的问题，不属实库的问题
