### ISSUE TITLE
add null safety

### ISSUE THREAD

**Issue by Ludy2015** [liranhao/recognition_qrcode#4]
flutter 2.0要求插件必须适配空安全

**Comment by liranhao** [comment]
> flutter 2.0要求插件必须适配空安全

好的，我本地还没更新到2.0，明天更新下

**Comment by liranhao** [comment]
> flutter 2.0要求插件必须适配空安全

你能帮忙fork一下改下吗？我这边环境没法升级，目前在用的app都没有升级，你fork改下，我合并下就行了

**Comment by Ludy2015** [comment]
我也还没升级呢 &nbsp;好几个项目 &nbsp;现在不敢升级呀





------------------ Original ------------------
From: liranhao ***@***.***&gt;
Date: Tue,Apr 6,2021 5:46 PM
To: liranhao/recognition_qrcode ***@***.***&gt;
Cc: LUDY2015 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [liranhao/recognition_qrcode] add null safety (#4)





  
flutter 2.0要求插件必须适配空安全
  
你能帮忙fork一下改下吗？我这边环境没法升级，目前在用的app都没有升级，你fork改下，我合并下就行了

**Comment by liranhao** [comment]
> 我也还没升级呢 &nbsp;好几个项目 &nbsp;现在不敢升级呀
> […](#)
> ------------------ Original ------------------ From: liranhao ***@***.***&gt; Date: Tue,Apr 6,2021 5:46 PM To: liranhao/recognition_qrcode ***@***.***&gt; Cc: LUDY2015 ***@***.***&gt;, Author ***@***.***&gt; Subject: Re: [liranhao/recognition_qrcode] add null safety (#4) flutter 2.0要求插件必须适配空安全 你能帮忙fork一下改下吗？我这边环境没法升级，目前在用的app都没有升级，你fork改下，我合并下就行了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

OKOK，我们快升级了，等升级后我改一下

**Comment by Ludy2015** [comment]
好的👌🏻





------------------ Original ------------------
From: liranhao ***@***.***&gt;
Date: Tue,Apr 6,2021 5:56 PM
To: liranhao/recognition_qrcode ***@***.***&gt;
Cc: LUDY2015 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [liranhao/recognition_qrcode] add null safety (#4)





  
我也还没升级呢 &nbsp;好几个项目 &nbsp;现在不敢升级呀
 …
 ------------------ Original ------------------ From: liranhao @.&gt; Date: Tue,Apr 6,2021 5:46 PM To: liranhao/recognition_qrcode @.&gt; Cc: LUDY2015 @.&gt;, Author @.&gt; Subject: Re: [liranhao/recognition_qrcode] add null safety (#4) flutter 2.0要求插件必须适配空安全 你能帮忙fork一下改下吗？我这边环境没法升级，目前在用的app都没有升级，你fork改下，我合并下就行了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
OKOK，我们快升级了，等升级后我改一下

**Comment by liranhao** [comment]
> 好的👌🏻
> […](#)
> ------------------ Original ------------------ From: liranhao ***@***.***&gt; Date: Tue,Apr 6,2021 5:56 PM To: liranhao/recognition_qrcode ***@***.***&gt; Cc: LUDY2015 ***@***.***&gt;, Author ***@***.***&gt; Subject: Re: [liranhao/recognition_qrcode] add null safety (#4) 我也还没升级呢 &nbsp;好几个项目 &nbsp;现在不敢升级呀 … ------------------ Original ------------------ From: liranhao @.&gt; Date: Tue,Apr 6,2021 5:46 PM To: liranhao/recognition_qrcode @.&gt; Cc: LUDY2015 @.&gt;, Author @.&gt; Subject: Re: [liranhao/recognition_qrcode] add null safety (#4) flutter 2.0要求插件必须适配空安全 你能帮忙fork一下改下吗？我这边环境没法升级，目前在用的app都没有升级，你fork改下，我合并下就行了 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. OKOK，我们快升级了，等升级后我改一下 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

已更新add null safe
