### ISSUE TITLE
扫描复杂的二维码会报错

### ISSUE THREAD

**Issue by BedRockGx** [liranhao/recognition_qrcode#6]
扫描 这么一段数据生成的二维码：{"code":1,"msg":"\u83b7\u53d6\u6210\u529f","data":{"appId":"wx42d6c48d12ecc5a0","timestamp":1628130342,"nonceStr":"d8hyadSFXOHtFnTI","signature":"11906e6df0cd5e5023e8e93976bbab450e4af63f"}})，就会报错，如果扫描一些简单的数据，没有什么问题

com.google.zxing.NotFoundException
E/flutter (21367): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(-1, Image parsing failed, null, null)
E/flutter (21367): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
E/flutter (21367): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter (21367): <asynchronous suspension>
E/flutter (21367): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (21367): #3      RecognitionQrcode.recognition (package:recognition_qrcode/recognition_qrcode.dart:16:33)
E/flutter (21367): #4      _BatchesWidgetState.build.<anonymous closure> (package:International_management/components/Material/materialWidget/batchesWidget.dart:60:35)
E/flutter (21367): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter (21367): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter (21367): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (21367): #8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (21367): #9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (21367): #10     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:259:7)
E/flutter (21367): #11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
E/flutter (21367): #12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:362:20)
E/flutter (21367): #13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (21367): #14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (21367): #15     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (21367): #16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (21367): #17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (21367): #18     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (21367): #19     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (21367): #20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (21367): #21     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (21367): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)

**Comment by liranhao** [comment]
这个错误是解析失败，原生端抛出来的异常，是iOS还是安卓，用的是别人的解析库，可能识别率太低了，你看下其他能不能扫出来

**Comment by liranhao** [comment]
内容超150字，手机和扫码枪不易扫描，轻缩短字符
