### ISSUE TITLE
识别不含二维码的图片会报错,导致没有回调

### ISSUE THREAD

**Issue by wenchang1989** [liranhao/recognition_qrcode#7]
[connection] nw_endpoint_handler_set_adaptive_read_handler [C10.1 157.119.174.252:80 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for read_timeout failed
[connection] nw_endpoint_handler_set_adaptive_write_handler [C10.1 157.119.174.252:80 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, dns)] unregister notification for write_timeout failed

目前解决是使用try catch兼容

**Comment by liranhao** [comment]
ios还是安卓？没有二维码会抛出code为-1的错误，需要用trycatch捕获一下，是返回的FlutterError

**Comment by liranhao** [comment]
![image](https://user-images.githubusercontent.com/15797388/146134417-8abb34f2-73b9-40db-8180-31337a58da01.png)
