### ISSUE TITLE
模拟器支持一下

### ISSUE THREAD

**Issue by DK3369** [liranhao/recognition_qrcode#9]
模拟器支持一下 ，现在模拟器无法使用

**Comment by liranhao** [comment]
> 模拟器支持一下 ，现在模拟器无法使用

Android还是iOS？

**Comment by con-9** [comment]
> > 模拟器支持一下 ，现在模拟器无法使用
> 
> Android还是iOS？

应该是android的，编译的时候报了这个错误，真机和模拟器都报了这个错误
dart sdk版本：2.18.0
recognition_qrcode版本：1.0.1+2
![image](https://user-images.githubusercontent.com/77889003/215939190-a147bb3e-ea03-42ae-974a-2300d5fbb22e.png)

**Comment by liranhao** [comment]
> 

Android系统版本发一下？我这边没遇到

**Comment by liranhao** [comment]
> > > 模拟器支持一下 ，现在模拟器无法使用
> > 
> > 
> > Android还是iOS？
> 
> 应该是android的，编译的时候报了这个错误，真机和模拟器都报了这个错误 dart sdk版本：2.18.0 recognition_qrcode版本：1.0.1+2 ![image](https://user-images.githubusercontent.com/77889003/215939190-a147bb3e-ea03-42ae-974a-2300d5fbb22e.png)

Android系统版本发一下？我这边没遇到

**Comment by con-9** [comment]
> > 
> 
> Android系统版本发一下？我这边没遇到

Android 11

**Comment by con-9** [comment]
> > > 
> > 
> > 
> > Android系统版本发一下？我这边没遇到
> 
> Android 11

非空版本是正常编译的

**Comment by con-9** [comment]
我在引用插件的时候去掉了版本号前面的箭头，使用指定版本可以正常编译，您最新发的1.0.2版本看看是否存在bug

**Comment by liranhao** [comment]
> 我在引用插件的时候去掉了版本号前面的箭头，使用指定版本可以正常编译，您最新发的1.0.2版本看看是否存在bug

好的

**Comment by dd9913762113** [comment]
iOS的模拟器

**Comment by liranhao** [comment]
1.0.2+1版本已修复这个问题
